/* ============================================================================
   Download Service
   ========================================================================= */

const archiver = require('archiver');
const { buildGameHTML } = require('./templateBuilder');

function createReadme(game) {
  return `# ${game.title}

Generated by Gaming Vibe Coding.

Open index.html in a browser to play.

Genre: ${game.genre}
Dimension: ${game.dimension}
`;
}

function streamGameZip({ game, res }) {
  const archive = archiver('zip', { zlib: { level: 9 } });
  const filename = `${game.id}.zip`;

  res.setHeader('Content-Type', 'application/zip');
  res.setHeader('Content-Disposition', `attachment; filename="${filename}"`);

  archive.pipe(res);
  archive.append(game.htmlString || buildGameHTML(game.gameJSON), { name: 'index.html' });
  archive.append(JSON.stringify(game.gameJSON, null, 2), { name: 'game.json' });
  archive.append(createReadme(game), { name: 'README.md' });

  if (Array.isArray(game.assetManifest) && game.assetManifest.length > 0) {
    archive.append(JSON.stringify(game.assetManifest, null, 2), { name: 'assets/manifest.json' });
  }

  archive.finalize();
}

module.exports = { streamGameZip };
